declare module 'react-native-ico-lodgicons' {
    import { ReactNode } from 'react';
    import { SvgProps, AdditionalProps } from 'react-native-svg';

    type iconNames = '1-star' |
      '2-stars-symbol' |
      '24-hours-circular-sign' |
      '24-hours-room-service' |
      '24-hours-sign' |
      '3-persons-or-person-number-three-symbol' |
      '3-persons-sign' |
      '3-stars-outlines' |
      '3-stars-symbol' |
      '4-stars-hotel-signal' |
      '4-stars-sign' |
      '5-persons-symbol' |
      '5-stars-sign' |
      '7-persons-male-silhouettes' |
      '7-persons-symbol' |
      '8-persons' |
      'add-button-sign-of-a-plus-symbol-inside-a-double-square-shape' |
      'add-hotel-symbol' |
      'air-conditioned' |
      'air-conditioner-sign' |
      'air-conditioner' |
      'airplane-black-shape-ascending-rotated-to-right' |
      'airplane-outline-pointing-up' |
      'alarm-clock-of-old-design' |
      'antenna-signal-symbol' |
      'arroba-sign' |
      'baby-crib' |
      'bag-for-ladies' |
      'bagagiste-with-baggage-on-a-platform-cart' |
      'baggage-cart-1' |
      'baggage-cart' |
      'baggage-on-an-elegant-hotel-platform-cart' |
      'baggage-on-platform-cart-outline' |
      'baggage-outline' |
      'balcony-and-door' |
      'bar-24-hours-rounded-square-signal' |
      'barbecue' |
      'basketball-ball-outline' |
      'bath-tub' |
      'bathroom-sink' |
      'bathrooms-for-men-and-women-outlines-sign' |
      'baths-marker-point' |
      'beach-signal' |
      'beach-view-of-sea-sun-and-seagulls-couple' |
      'bed-for-a-couple' |
      'bed-for-two-persons' |
      'bed-for-two' |
      'bed-side-view' |
      'bedroom-card' |
      'beer-jar' |
      'bell-boy-portrait' |
      'bell-boy-with-baggage' |
      'bike-parking-signal' |
      'bike-shape' |
      'bike-zone-signal' |
      'bikes-sale-sign-in-dollars' |
      'bingo' |
      'black-beach-umbrella' |
      'blender-outline' |
      'blu-ray-sign' |
      'bowling-ball-and-pin' |
      'boy-with-headphones' |
      'broom-black-silhouette' |
      'brush-outline-in-diagonal' |
      'buffet' |
      'bunk-bed' |
      'burger-side-view-outline' |
      'bus-parking-sign' |
      'cable-tv-sign-with-monitor' |
      'calendar-daily-page-on-day-31' |
      'call-a-taxi-symbol' |
      'call-cost-symbol' |
      'canoe-boat-with-rowing' |
      'car-parking-signal' |
      'caravan-can-outline-for-nomad-lifestyle' |
      'carpet-hanging-of-a-rope' |
      'casino-chip-with-number-11' |
      'casino-map-marker' |
      'ceiling-covered-parking-signal' |
      'chapel' |
      'chef-toque-outline' |
      'chimney-with-fire' |
      'church-cross' |
      'church-localization-marker-sign' |
      'cigarette' |
      'clock-at-twelve' |
      'closed-baggage' |
      'cloth-hanging-of-a-hanger' |
      'cocktail-glass' |
      'cocktails-24-hours' |
      'coffee-cup-of-hot-drink-black-silhouette' |
      'coffee-jar' |
      'coffee-shop-marker' |
      'collective-elevator-sign' |
      'comb-on-hair' |
      'compact-disc' |
      'cot-black-silhouette-side-view' |
      'couple-in-sauna' |
      'couple-of-persons-resting-on-a-bunk' |
      'covered-swimming-pool-symbol' |
      'covered-swimming-pool-with-roof' |
      'credit-card-payment' |
      'dancer-with-music' |
      'delete-hotel-symbol' |
      'delete-transport-symbol' |
      'descend-signal' |
      'dices-couple' |
      'directional-arrows-signals-on-a-pole' |
      'disability' |
      'disco-ball-of-small-mirrors-with-musical-note-symbol' |
      'do-not-disturb-hanging-signal-for-hotel-doors' |
      'do-not-disturb-signal-to-hang-from-hotel-doors' |
      'do-not-entry-signal-for-hotel-door' |
      'do-not-pass-hanging-signal-for-door' |
      'do-not-pass-signal-for-hang-on-doors' |
      'do-not-swim-sign' |
      'dog-shape-outline-in-a-square' |
      'dont-smoke-signal-of-prohibition' |
      'dont-smoke-symbol' |
      'down-stair-symbol' |
      'drink-glass' |
      'drying-machine-outline' |
      'dumbbell-outline' |
      'dvd-player-outline' |
      'dvd-sign' |
      'dvd' |
      'eight-persons-or-person-number-8-symbol' |
      'eight-persons-or-person-number-8' |
      'eight-persons-symbol' |
      'eight-persons' |
      'elevator-buttons' |
      'elevator-for-people' |
      'elevator-symbol' |
      'elevator-with-one-person-inside-and-up-and-down-arrows-at-sides' |
      'english-receptionist' |
      'entertainment-area-symbol-with-abc-cubes-and-house-outline' |
      'euro-bills' |
      'exit-door-symbol' |
      'exit-signal' |
      'extinguisher-outline' |
      'fan-black-silhouette' |
      'fan-of-square-shape-outline' |
      'fan-tool' |
      'fast-food-placeholder' |
      'fax-top-view' |
      'firewood-sale-symbol' |
      'firewood-signal' |
      'first-aid-case' |
      'first-aid-kit' |
      'five-persons-or-person-number-five' |
      'five-persons-silhouettes' |
      'five-persons-symbol-1' |
      'five-persons-symbol' |
      'five-stars-hotel-signal-1' |
      'five-stars-hotel-signal' |
      'five-stars-quality-symbol' |
      'flowers-shop' |
      'food-covered-by-a-bell-shape-outline' |
      'food-covered' |
      'food-in-bedroom' |
      'food-service-to-bedroom' |
      'four-persons-or-person-number-4-symbol' |
      'four-persons-sign' |
      'four-persons-symbol' |
      'four-persons' |
      'four-stars' |
      'free-wifi-signal' |
      'french-receptionist' |
      'gambling-coins-machine-with-winner-result-of-three-seven' |
      'garage-with-roof-and-parked-car' |
      'garage' |
      'gas-cylinder-outline' |
      'gift-box-outline' |
      'glass-with-water' |
      'golf-ball-and-tee' |
      'golf-elements' |
      'golf-hole-with-a-flag' |
      'golf-putter-ball-and-tee' |
      'gym-dumbbell-black-silhouette' |
      'hair-cutting' |
      'hairdryer-outline' |
      'hairdryer' |
      'half-star-shape' |
      'hammock-with-a-person-lying-and-resting-on-it' |
      'hand-with-a-dumbbell' |
      'hanger-line-tool' |
      'hdmi-cable' |
      'hdmi-high-definition-multimedia-interface' |
      'headphones' |
      'hearts-outlines-of-gross-lines' |
      'heating-black-tool' |
      'heating-device-for-winter' |
      'heating-device-in-a-bedroom' |
      'heating' |
      'hot-cakes' |
      'hot-coffee-mug-outline' |
      'hot-towels' |
      'hotel-1-star-signal' |
      'hotel-2-stars-signal' |
      'hotel-building' |
      'hotel-check-symbol' |
      'hotel-key-outline-in-horizontal-position' |
      'hotel-of-three-stars-signal' |
      'hotel-of-two-stars-quality' |
      'hotel-reception-bell' |
      'hotel-reception-outline' |
      'hotel-search-interface-symbol' |
      'hotel-sign' |
      'ice-cubes-in-a-square' |
      'indoor-temperature' |
      'info-sign' |
      'information-letter-sign-outline' |
      'information-marker' |
      'informative-map' |
      'international-reception-worker' |
      'international-telephone-symbol-outline' |
      'iron-outline-side-view' |
      'iron-table-outline-from-side-view' |
      'italian-receptionist-saying-ciao' |
      'jacuzzi' |
      'key-with-label' |
      'laptop-with-arroba-sign-on-screen' |
      'left-and-right-arrows-on-a-thin-column' |
      'letter-h-hotel-outline-with-five-stars' |
      'library-placeholder' |
      'library-symbol-outline' |
      'lobby-sign' |
      'love-symbol-of-a-heart-outline-in-a-square' |
      'map-location' |
      'margarita-glass-drink' |
      'massage-session' |
      'mastercard' |
      'microwaves' |
      'minibar' |
      'minisplit' |
      'money-bills' |
      'monitor-screen-with-keyhole-shape' |
      'musical-note-outline-symbol-inside-two-squares' |
      'nine-persons-symbol-1' |
      'nine-persons-symbol' |
      'nine-persons' |
      'no-animals-symbol' |
      'no-cats-accepted' |
      'no-food-allowed' |
      'no-pets-allowed-symbol' |
      'no-vacancy-signal' |
      'one-bed-for-two' |
      'one-star-hotel-sign' |
      'one-star-hotel-signal' |
      'one-star-symbol' |
      'online-location' |
      'open-garage-under-the-sun' |
      'outdoors-table-with-chairs-couple-and-umbrella' |
      'oven' |
      'padlock-symbol-of-security-24-hours-a-day' |
      'parking-for-disabled-persons-sign' |
      'parking-garage-sign-in-rounded-square' |
      'parking-meter' |
      'parking-sign' |
      'parking-square-signal' |
      'parking-ticket' |
      'parking' |
      'pc-computer-and-monitor-outlines' |
      'persian-blinds-outline' |
      'person-ascending-on-electric-stairs' |
      'person-enjoying-jacuzzi-hot-water-bath' |
      'person-in-sauna-treatment' |
      'person-in-spa' |
      'person-lying-in-an-artificial-solar-tan-bed-for-indoor-bronze-skin-tone' |
      'person-lying-on-a-beach-under-an-umbrella' |
      'person-number-7-or-seven-persons' |
      'person-riding-on-a-bicycle-side-view-silhouette' |
      'person-rowing-on-a-kayak' |
      'person-running-on-a-treadmill-silhouette-from-side-view' |
      'person-silhouette-in-sauna' |
      'person-sweating-in-a-sauna' |
      'personal-elevator-signal' |
      'persons-in-group-of-four' |
      'persons-nine-silhouettes' |
      'persons-number-symbol' |
      'pets-circular-sign' |
      'photo-camera-frontal-outline' |
      'plate-fork-and-knife' |
      'poker-cards' |
      'poker-playing-cards' |
      'pool-eight-ball-and-stick' |
      'pool-rectangular-hanging-sign' |
      'pool-table-top-view' |
      'port-map-marker-point' |
      'postcard-back-side' |
      'pound-bills' |
      'private-baggage-box-with-key' |
      'private-swimming-pool-sign' |
      'prohibition-of-wood-cutting-sign' |
      'public-elevator-sign' |
      'public-swimming-pool-sign' |
      'queen-size-bed' |
      'question-mark-inside-a-box-outline' |
      'rack-of-tall-thin-shape-for-hanging-clothes' |
      'radio-of-rectangular-rounded-simple-design' |
      'radio-outline' |
      'radio' |
      'registered-sign' |
      'restaurant-locator-for-map' |
      'restaurant-symbol-of-utensils' |
      'room-service-signal-for-hotel-doors' |
      'room-service-time' |
      'room-service' |
      'roulette' |
      'roundabout' |
      'rss-symbol-on-tablet-screen' |
      'safe-box-variant-outline' |
      'safe-box-with-wheel-system' |
      'sandals-pair-outline' |
      'satellite-tv-monitor-symbol' |
      'search-for-transport-interface-symbol' |
      'security-box-closed-outline' |
      'security-box' |
      'seven-persons-or-person-number-7-symbol-outline' |
      'seven-persons-symbol' |
      'shopping-bag-outline' |
      'shopping-cart-in-a-circle' |
      'shopping-zone-marker' |
      'shower' |
      'single-bed-outline' |
      'single-bed' |
      'six-persons-1' |
      'six-persons-2' |
      'six-persons-or-person-number-6-symbol' |
      'six-persons-sign' |
      'six-persons' |
      'slide-to-swimming-pool-water' |
      'smoking-not-allowed-symbol' |
      'smoking-prohibition-circular-signal' |
      'snow-weather-symbol' |
      'snowflake-weather-symbol' |
      'soccer-ball-outline' |
      'sofa-of-one-place-outline' |
      'sofa-of-three-places-outline' |
      'spoon-fork-and-knive-silhouettes-restaurant-symbol' |
      'stair-of-a-swimming-pool' |
      'stairs-in-a-square-sign' |
      'star-for-number-one' |
      'star-number-3' |
      'star-number-five' |
      'star-outline-in-a-circle-line' |
      'star-outline-of-five-points' |
      'star-with-number-4' |
      'star-with-number-two' |
      'store-with-open-signal' |
      'sweet-bread-in-a-square' |
      'swimmer-in-water-waves-under-the-sun' |
      'swimmer-swimming-in-an-interior-covered-swimming-pool' |
      'swimming-pool-covered-with-roof' |
      'swimming-pool-location-marker-for-maps' |
      'swimming-pool-location-marker' |
      'swimming-pool-opened-under-sunlight' |
      'swimming-pool-roofless-under-the-sun' |
      'swimming-pool-signal' |
      'swimming-pool-water-waves-with-ladder' |
      'swimming-pool-zone-marker' |
      'taxi-cab' |
      'taxi-outline' |
      'telephone-24-hours-sign' |
      'telephone-auricular-outline' |
      'telephone-outline-from-top-view' |
      'tennis-ball-and-raquet' |
      'tennis-racket-and-ball' |
      'tennis-raquet-and-ball' |
      'three-persons-sign' |
      'three-persons-silhouettes' |
      'three-persons' |
      'three-stars-hotel-sign' |
      'toaster-outline-tool' |
      'toilet-black-silhouette' |
      'toilet-hanging-sign' |
      'toilet-outline-in-a-square' |
      'towels-sale-symbol-with-dollar-sign' |
      'towels-with-checked-symbol' |
      'traveler-and-hotel-bed-outline' |
      'tub' |
      'tv-monitor' |
      'two-persons-or-person-number-two' |
      'two-persons-signal' |
      'two-persons-silhouettes' |
      'two-persons-symbol-1' |
      'two-persons-symbol' |
      'two-stars-sign' |
      'umbrella-opened-outline' |
      'up-stairs-square-signal' |
      'urban-rest-hotel-sign-with-minus-symbol' |
      'vacancy-sign' |
      'ventilation-of-bedroom' |
      'washing-machine' |
      'wifi-usb-device-outline' |
      'wifi-zone-marker' |
      'wifi-zone-rectangular-signal' |
      'wifi-zone-symbol' |
      'wine-locator' |
      'yen-bills';

    type iconColors = ;

    type backgroundType = 'circle' | 'rect' | 'button';

    type colorsType = Record<iconColors, string>;

    type positionType = 'top' | 'bottom' | 'right' | 'left' |
      'top_right' | 'top_left' | 'bottom_right' | 'bottom_left';

    type backgroundTypeObj = {
      type?: backgroundType;
      color?: string;
      radius?: number;
      borderRadius?: number;
    };

    type badgeTypeObj = {
      value?: number | string;
      fontSize?: string;
      position?: positionType;
      color?: string;
      colors: colorsType;
      backgroundColor?: string;
      radius?: number;
    };

    interface IconProps {
      name: iconNames;
      width?: number;
      height?: number;
      color?: string;
      colors: colorsType;
      stroke?: number;
      background?: backgroundType | backgroundTypeObj;
      badge?: number | string | badgeTypeObj;
    }

    const Icon: (props: IconProps & SvgProps & AdditionalProps) => ReactNode;

    export { iconNames };
    export default Icon;
}
